env:
  MAVEN_OPTS: -Xmx4g -Xms1g -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.count=3
jobs:
  mvn:
    if: github.repository == 'apache/servicecomb-pack'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Cache Maven Repository
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository/

          !~/.m2/repository/org/apache/servicecomb

          '
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Show the first log message
      run: git log -n1
    - continue-on-error: true
      if: ${{ success() }}
      name: Build and test
      run: ./mvnw clean install -Pdocker -B
    - continue-on-error: true
      if: ${{ failure() }}
      name: Upload unit test results
      uses: actions/upload-artifact@v2
      with:
        if-no-files-found: ignore
        name: surefire-reports
        path: ./**/target/surefire-reports/
    - continue-on-error: true
      if: ${{ success() }}
      name: Verify demo
      run: ./mvnw clean verify -f demo -Pdemo -Pdocker -Ddocker.useColor=false -Ddocker.showLogs
        -B
    - continue-on-error: true
      if: ${{ success() }}
      name: Verify Acceptance tests
      run: ./mvnw clean verify -f acceptance-tests -Pdemo -Pdocker -Ddocker.useColor=false
        -Ddocker.showLogs -B
    strategy:
      fail-fast: false
      matrix:
        java:
        - '8'
        - '11'
    timeout-minutes: 180
name: master pr build
on:
  repository_dispatch:
    types: trigger-ga___master-pr-build.yaml
